### DISCUSSION TITLE
API timeout running on large repository

### DISCUSSION THREAD

**Discussion by alclonky** [mend/renovate-ce-ee#283] [Q&A]
We are getting timeouts calling /status or  / with an liveness probe when renovate runs for an large repo 
this repos has a renovate run duration of 15 minutes
```
    "stats": {
         "managers": {
           "dockerfile": {"fileCount": 6, "depCount": 6},
           "gradle": {"fileCount": 69, "depCount": 16560},
           "html": {"fileCount": 3, "depCount": 6},
           "npm": {"fileCount": 3, "depCount": 22},
           "nuget": {"fileCount": 2, "depCount": 0}
         },
         "total": {"fileCount": 83, "depCount": 16594}
```

We are running renovate 1.0.0-rc.3 on an OpenShift 4.4 Cluster 
CPU Usage is between 700 and 800m, Memory Usage around 8 GB 

if I look at the logs during such timeout situation the run seems "stuck"

**Comment by rarkins** [comment]
> this repos has a renovate run duration of 15 minutes

From other conversations we had by email, I think you mean you cron the scheduled task every 15 minutes? That doesn't actually limit the duration.

Does this repository eventually *finish*?

**Comment by alclonky** [comment]
No thats the duration it need until finished and also the cron

**Comment by Reamer** [comment]
We also see dropouts of the API while the cron checks repositories.
Maybe a dedicated thread which responds to API requests will help here.
![grafik](https://user-images.githubusercontent.com/454320/208618852-20c5ba42-4329-4a6d-a930-eabf4c309468.png)

**Reply by Reamer** [reply]
We have increased our timeout from one second from the [Helm File](https://github.com/mend/renovate-on-prem/blob/087f60c43bc2da8b1a7064360f6268b412b9a046/helm-charts/whitesource-renovate/values.yaml#L139-L156) to ten seconds. So far, no other errors have appeared.

```
...
      readinessProbe:
        httpGet:
          path: /
          port: renovate
          scheme: HTTP
        timeoutSeconds: 10
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 3
...
      livenessProbe:
        httpGet:
          path: /
          port: renovate
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 10
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 3
...
```
