### DISCUSSION TITLE
Inject additional secrets into deployment

### DISCUSSION THREAD

**Discussion by ajhcpt** [mend/renovate-ce-ee#504] [Q&A]
Hi, I would like to be able to inject additional secrets. In my particular case I would like to provide my ECR access key details as secrets. As far as I can tell this is not possible at the moment, is that correct?

Would it be possible to adjust the deployment template to allow for this. Similar to what is done for extraEnvVars. Something like this in the deployment template:

```yaml
            {{- with .Values.renovate.extraSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: {{ .refKey }}
            {{- end }}
```
and in the chart:
```yaml
  extraSecrets:
    - name: AWS_SECRET_KEY_ID
      refKey: awsSecretKeyId
```
