### DISCUSSION TITLE
Connecting self hosted Renovate community edition to Bitbucket cloud

### DISCUSSION THREAD

**Discussion by nitin-vavdiya** [mend/renovate-ce-ee#628] [Q&A] [answered]
Hi there, 

I am trying to connect a self-hosted Renovate community edition to Bitbucket cloud.
I am installing renovating using helm chart in the kubernetes cluster.

In bucket, I create an app password for my user with repository write permissions, my values.yaml as below:

```
renovate:
  mendRnvAcceptTos: 'y'
  mendRnvPlatform: 'bitbucket-server'
  mendRnvEndpoint: "https://api.bitbucket.org"
  mendRnvBitbucketUser: "username"
  mendRnvBitbucketPat: "app password"
  mendRnvLicenseKey: my-key
```

While running the container, it gives the below error message from :

```
"body": "{\"type\": \"error\", \"error\": {\"message\": \"Token is invalid or not supported for this endpoint.\"}}"
```

Can you please help me what should be the value of `mendRnvEndpoint`, we are using Bitbucket cloud. We are accessing bitbuckt cloud using `https://bitbucket.org/my_workspace/workspace/overview/`
