### DISCUSSION TITLE
Self hosted rest api always responds 403 (and I'm sure it's me but would like to know what I'm doing wrong)

### DISCUSSION THREAD

**Discussion by zenbones** [mend/renovate-ce-ee#683] [Q&A] [answered]
How are you running Renovate?
Self-hosted Renovate

If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.
GitHub, docker image ghcr.io/mend/renovate-ce:9.8.0

Please tell us more about your question or problem
I'm just trying to auth to the rest api. I have...
MEND_RNV_ADMIN_API_ENABLED: true
MEND_RNV_SERVER_API_SECRET=abc123 # yes, I know this is unsafe and I'll change it as soon as I know I can make a rest call

The GET to http:///health return 200
The call to GET https:///api/job/queue returns 403

I am including the Authorization header...

Basic :abc123 | base64 encoding as in...
Basic dXNlcjphYmMxMjM= # which is the base64 encode of 'user:abc123'

Not sure what the is supposed to be, but I've tried the base64 encode of just 'abc123', 'abc123:abc123', 'renovate:abc123', etc. The logs simply state...

DEBUG: Received API request
"url": "/api/job/queue",
"method": "GET",
"protocol": "http",
"agent": "insomnia/11.0.1"
DEBUG: Rejecting unauthenticated request
"agent": "insomnia/11.0.1",
"resource": "/api/job/queue"

I have looked for docs on the proper auth header format but all I've found is a google AI response telling me to use the value of MEND_RNV_SERVER_API_SECRET as the password. I'm sure this is me, and I'm missing something easy, but any help appreciated.

**Comment by Gabriel-Ladzaretti** [comment]
Leave the auth schema empty and it should work.
https://github.com/mend/renovate-ce-ee/blob/main/docs/api.md#enabling-and-authentication

As for why the health works, its because it is unauthenticated as it is supposed to be internal if i remember correctly.

**Reply by zenbones** [reply]
I do know why the health works. I included as an indicator that the service was running and healthy (no clue what internal checks the endpoint does, if any, but the response shows at least a running http daemon).

As for 'leaving the auth schema empty', what auth schema? This may be my fault for not sharing my config. Allow me rectify that...

docker-compose.yaml
```
services:
  renovate-ce:
    image: ghcr.io/mend/renovate-ce:9.8.0
    user: "1000:1000"
    ports:
      - "80:8080"
    env_file:
      - ../env/mend-renovate.env
      - ../env/github.env
    environment:
      LOG_LEVEL: debug 
     MEND_RNV_REQUEST_LOGGER_ENABLED: true
      MEND_RNV_ADMIN_API_ENABLED: true
      MEND_RNV_REPORTING_ENABLED: true
      MEND_RNV_LOG_HISTORY_DIR: /logs
      MEND_RNV_SQLITE_FILE_PATH: /db/renovate-db.sqlite
      RENOVATE_REPOSITORY_CACHE:
    volumes:
      - /opt/renovate/secret:/secret
      - /opt/renovate/job-logs:/logs
      - /opt/renovate/db:/db
```
github.env
```
MEND_RNV_PLATFORM=github
MEND_RNV_GITHUB_APP_ID=12345678
MEND_RNV_GITHUB_PEM_FILE_PATH=/secret/forio-renovate.private-key.pem
MEND_RNV_WEBHOOK_SECRET=somesecret
```

mend-renovate.env
```
MEND_RNV_LICENSE_KEY=eyJsaW1pdCI6IjEwIn0=.30440220457941b71ea8eb345c729031718b692169f0ce2cf020095fd328812f4d7d5bc1022022648d1a29e71d486f89f27bdc8754dfd6df0ddda64a23155000a61a105da2a1
MEND_RNV_ACCEPT_TOS=Y
MEND_RNV_SERVER_API_SECRET=abc123
```

Now, what auth schema? Have I made some mistake in these configurations?

Thank you for your time and attention.
