### ISSUE TITLE
Unable to start new renovate-ce container due to database error when mapping db to volume

### ISSUE THREAD

**Issue by lluiscab** [mend/renovate-ce-ee#342]
The new `renovate-ce` image fails to start when using a SQLITE database mounted with a volume to a local folder

**docker-compose.yml**

```yml
version: '3.6'
services:
  renovate:
    container_name: renovate
    image: ghcr.io/mend/renovate-ce:6.0.0-full
    restart: always
    environment:
      - LOG_LEVEL=DEBUG

      # Provide Mend License and accept Terms of Service
      - MEND_RNV_ACCEPT_TOS=y

      # Provide connection details for the GitLab Bot
      - MEND_RNV_PLATFORM=gitlab
      - MEND_RNV_ENDPOINT=<redacted>
      # - MEND_RNV_WEBHOOK_SECRET # Optional: defaults to 'renovate'

      # Optional settings for Mend Renovate
      - MEND_RNV_ADMIN_API_ENABLED=true
      - MEND_RNV_SERVER_API_SECRET=secret
      - MEND_RNV_SQLITE_FILE_PATH=/db/renovate.sqlite

      # Core Renovate settings
      - RENOVATE_NPMRC="registry=<redacted>"
      - RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS=^.*$$
      - RENOVATE_ALLOW_POST_UPGRADE_COMMAND_TEMPLATING=true

    env_file: secrets.env
    ports:
      - '9050:8080'
    volumes:
      # Mount tmp folder for persistance & easier management of renovate cache
      - type: bind
        source: ./data/tmp
        target: /tmp/
        read_only: false

      # Mount db folder for persistance
      - type: bind
        source: ./data/db
        target: /db/
        read_only: false

    # Log to JSON File with 50MB limit
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
```

**secrets.env**

```
# Renovate Free License Key
MEND_RNV_LICENSE_KEY=

#Personal Access Token for the @Renovate Bot user
MEND_RNV_GITLAB_PAT=

# This Github token belongs to the user `<redacted>` and has been created without an expiry date.
# It allows for `read:user` and it's used by Renovate to fetch dependency release information such as changelogs.
GITHUB_COM_TOKEN=
```

**Container logs**

```sh
$ docker compose up
[+] Running 1/1
 ✔ Container renovate  Recreated                                                                                                                                                                        0.5s 
Attaching to renovate
renovate  | DEBUG: Using RE2 as regex engine
renovate  |  INFO: Validating terms of service agreement
renovate  |        "input": "y"
renovate  |  INFO: Validating Mend license key
renovate  |  INFO: This is a CORPORATE Mend Renovate license, registered to: <redacted>. It was registered by <redacted>
renovate  | DEBUG: Initializing...
renovate  | DEBUG: Initializing sqlite
renovate  |        "filename": "/db/renovate.sqlite"
renovate  | FATAL: failure initializing Renovate community edition - exiting...
renovate  |        "err": {
renovate  |          "errno": 14,
renovate  |          "code": "SQLITE_CANTOPEN",
renovate  |          "message": "SQLITE_CANTOPEN: unable to open database file",
renovate  |          "stack": "Error: SQLITE_CANTOPEN: unable to open database file"
renovate  |        }
renovate exited with code 0
```

**Permissions of folders inside the `data` directory:**
```
drwxr-xr-x 	2 root     root     4.0K Oct  2 11:15 db
drwxrwxrwx 	9 root     root     4.0K Oct  2 11:13 tmp
```

**Observations:**

- If I remove the `MEND_RNV_SQLITE_FILE_PATH` then the container will start successfully (I assume this means without a database)
- If I remove the `db` volume and change the value of `MEND_RNV_SQLITE_FILE_PATH` to `/tmp/renovate.sqlite`, then the container starts successfully (For obvious reasons I don't want to store a database in a temporal folder)
- If I add `user: "0:0"` to my `docker-compose.yml` file, then the container starts successfully.

It seems like there's some sort of permissions issue when renovate has to create / read the database file from a volume.

**Comment by justo-mend** [comment]
Thanks for raising the issue (and for the excellent description/documentation).

We will look into this.

**Comment by Gabriel-Ladzaretti** [comment]
Please ensure that `./data/db` exists and that the process has the necessary write permissions for it.

**Comment by Gabriel-Ladzaretti** [comment]
can grant group write permissions to the 'db' folder? This would enable the container to have the necessary write permissions to create and modify the SQLite file.

**Comment by lluiscab** [comment]
I've been able to start the container by running `chmod 777` on the `db` folder, but I have to say, it seems a bit wrong given that the folder is already owned by the `root` user and group with 755 permissions. Should I have kept the 775 permissions and instead change the directory owner to a user that matches the container uid and gid?

**Comment by NINNiT** [comment]
The same issue emerges when mapping a named dockervolume to `/db/`.

```
services:
  ...
  volumes:
     - renovate-data:/db/
volumes:
  renovate-data:
```

Using a directory/bind-mount and setting `777` works, however that can't be the way forward.
