### ISSUE TITLE
Error after updating Renovate from v5 to v6: "MEND_RNV_GITHUB_APP_KEY is invalid"

### ISSUE THREAD

**Issue by fchimpan** [mend/renovate-ce-ee#360]
I recently upgraded Renovate from version 5.0.1 to version 6.1.1-full and encountered an error. The error message I received is "MEND_RNV_GITHUB_APP_KEY is invalid".

**Details**:

With version 5, I had the following `compose.yaml` configuration and it was working correctly:
```yaml
version: '3.6'
services:  
  renovate:
    image: whitesource/renovate:5.0.1
    restart: always
    environment:
      ACCEPT_WHITESOURCE_TOS: y
      LICENSE_KEY: ${RENOVATE_LICENSE_KEY}
      RENOVATE_PLATFORM: github
      # GitHub Enterprise API endpoint, include the trailing slash
      RENOVATE_ENDPOINT: ${GITHUB_ENTERPRISE_SERVER_ENDPOINT}
      GITHUB_APP_ID: 2
      GITHUB_COM_USERNAME: ${GITHUB_COM_USERNAME}
      # Personal Access Token for github.com (used for retrieving changelogs and reading private packages)
      GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      SCHEDULER_CRON: "0 * * * *"
    ports:
      - "80:8080" # Receive webhooks on port 80
    volumes:
      - "./renovate.private-key.pem:/usr/src/app/renovate.private-key.pem:ro"
      - "./config.js:/usr/src/app/config.js:ro"
      - "./.gitconfig:/home/ubuntu/.gitconfig:ro"
```

For version 6, I updated the compose.yaml to:
```yaml
version: "3.6"
services:
  renovate:
    image: ghcr.io/mend/renovate-ce:6.1.1-full
    restart: always
    environment:
      MEND_RNV_ACCEPT_TOS: y
      MEND_RNV_LICENSE_KEY: ${RENOVATE_LICENSE_KEY}
      MEND_RNV_PLATFORM: github
      # GitHub Enterprise API endpoint, include the trailing slash
      MEND_RNV_ENDPOINT: ${GITHUB_ENTERPRISE_SERVER_ENDPOINT}
      MEND_RNV_GITHUB_APP_ID: 2
      GITHUB_COM_USERNAME: ${GITHUB_COM_USERNAME}
      # Personal Access Token for github.com (used for retrieving changelogs and reading private packages)
      GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
      MEND_RNV_WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      MEND_RNV_CRON_JOB_SCHEDULER: "0 * * * *"
    ports:
      - "80:8080" # Receive webhooks on port 80
    volumes:
      - "./renovate.private-key.pem:/usr/src/app/renovate.private-key.pem:ro"
      - "./config.js:/usr/src/app/config.js:ro"
      - "./.gitconfig:/home/ubuntu/.gitconfig:ro"
```

After making these changes, I received the following error:

```sh
renovate-renovate-1  | FATAL: failure initializing Renovate community edition - exiting...
renovate-renovate-1  |        "err": {
renovate-renovate-1  |          "message": "MEND_RNV_GITHUB_APP_KEY is invalid",
renovate-renovate-1  |          "stack": "Error: MEND_RNV_GITHUB_APP_KEY is invalid\n    at Object.mustInitialize (/usr/src/app/src/community.js:1:31927)\n    at Object.mustInitialize (/usr/src/app/src/community.js:1:34639)\n    at t.getPlatform (/usr/src/app/src/community.js:1:51560)\n    at /usr/src/app/src/community.js:1:62306\n    at async /usr/src/app/src/community.js:1:61660\n    at async /usr/src/app/src/community.js:1:61506"

```

I have verified that the secret key exists and is correct.

Would appreciate any guidance on what might be the issue and how to resolve it. Thank you!
