### ISSUE TITLE
Breaking change in 9.9.0: config.js can't be read because it's treated as ESM

### ISSUE THREAD

**Issue by dennisameling** [mend/renovate-ce-ee#695]
Our self-hosted Renovate instance got updated to 9.9.0 today, where you [converted](https://github.com/mend/renovate-ce-ee/releases/tag/9.9.0) the project to ESM. We're now seeing the following in the logs:

```
Error parsing config file due to unresolved variable(s): module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/usr/src/app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

Our config file is mounted as `/usr/src/app/config.js` in the container, [as recommended in your docs](https://github.com/mend/renovate-ce-ee/blob/main/docs/configuration-options.md#configure-renovate-core).

We tried renaming the file to `config.cjs`, but that doesn't get picked up by the Renovate container at all. The logs now indicate:

```
No config file found on disk - skipping
```

We'll downgrade to 9.8.0 for the time being.

**Comment by nabeelsaabna** [comment]
Hi @dennisameling can you please share a bit more logs
mainly the log message `Executing Renovate run command`

**Comment by nabeelsaabna** [comment]
https://github.com/mend/renovate-ce-ee/releases/tag/9.9.1

**Comment by derritter88** [comment]
Can confirm this works for me 👍 
Cheers @nabeelsaabna

**Comment by dennisameling** [comment]
@nabeelsaabna unfortunately, 9.9.1 doesn't fix the issue for us. I'm again seeing `No config file found on disk - skipping` in our logs, together with a bunch of `Package lookup failures` because Renovate doesn't load `/usr/src/app/config.js` in which we've defined a bunch of `hostRules` for our private packages.

Let me know if you need more logs.

**Comment by dennisameling** [comment]
> Maybe you forgot to rename it back to *.js?

I renamed it back already.

Just SSH'ed into the container and I noticed that the app directory moved from `/usr/src/app` to `/usr/src/mend` in 9.9.1:

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/5bec9495-083e-4774-9694-bc4077e53605" />

> make sure the actual path matches RENOVATE_CONFIG_FILE

That env variable doesn't seem to be set at the container level. Also, the Renovate [docs](https://github.com/renovatebot/renovate/blob/main/docs/development/configuration.md#configuration-file) mention the following:

> You can override default configuration using a configuration file, with default name `config.js` in the working directory. If you need an alternate location or name, set it in the environment variable `RENOVATE_CONFIG_FILE`.

Given that the working directory seems to have changed to `/usr/src/mend`, I think I can either copy my `config.js` file into `/usr/src/mend` instead of `/usr/src/app` or explicitly set `RENOVATE_CONFIG_FILE` to `/usr/src/app/config.js`. Let me try the latter now and report back here.

**Comment by dennisameling** [comment]
Explicitly setting `RENOVATE_CONFIG_FILE` to `/usr/src/app/config.js` fixed the issue for us.

I think we can summarize this as follows:

### Through version 9.8.0
- Renovate CE/EE was a CJS project living in the `/usr/src/app` directory in the Docker image
- If no explicit `RENOVATE_CONFIG_FILE` env variable was set, Renovate would automatically look for `/usr/src/app/config.js` because [its default behavior is to try and find this file in the working directory](https://github.com/renovatebot/renovate/blob/main/docs/development/configuration.md#configuration-file).
- Renovate CE/EE mentions in their docs that users can mount a config file to `/usr/src/app/config.js` for the config file to be picked up automatically:

> The core Renovate OSS functionality can be configured using environment variables (e.g. `RENOVATE_XXXXXX`) or via a `config.js` file that you mount inside the Mend Renovate container to `/usr/src/app/config.js`. Both settings should be done in the worker.

### Starting with 9.9.1
- Renovate CE/EE is an ESM project living in the `/usr/src/mend` directory in the Docker image
- If no explicit `RENOVATE_CONFIG_FILE` env variable is set, Renovate will automatically look for `/usr/src/mend/config.js` and expects that file to be in the ESM format

So since we were mounting the (CJS) config file to `/usr/src/app/config.js` as per your docs, this no longer works as of 9.9.1 and we had to explicitly set `RENOVATE_CONFIG_FILE` to point to the old location. You may want to update your docs accordingly because of this change.

Thanks for the help!

**Comment by nabeelsaabna** [comment]
@dennisameling 
I think it might be better to let Renovate CE/EE handle this specific case
if `/usr/src/app/config.js` exists, set ``RENOVATE_CONFIG_FILE=/usr/src/app/config.js` before a Renovate job start.

otherwise it will still be a breaking change.

In addition adding `/usr/src/mend/config.js` will not work due to a couple of reasons
* `/usr/src/mend/` is ESM while Renovate is CJS
* `/usr/src/mend/` is not the `cwd` of jobs

**Comment by leshasmlesha** [comment]
> Dont put it besides the package json under /usr/src/mend, it will break it unless u covert ur cfg to esm.
> 
> How are u mounting ur cfg?
> 
> If u are using
> 
> [renovate-ce-ee/helm-charts/mend-renovate-ce/values.yaml](https://github.com/mend/renovate-ce-ee/blob/00ac34421a6f6784b9ee64e73baf3484aba03f42/helm-charts/mend-renovate-ce/values.yaml#L163)
> 
> Line 163 in [00ac344](/mend/renovate-ce-ee/commit/00ac34421a6f6784b9ee64e73baf3484aba03f42)
> 
>  config: | 
> 
> It supposed to work out of the box

No, it doesn't work. I use exactly this method, but after the update it doesn't work, here is an example
```yml
config: |
        module.exports = {
          registryAliases: {
            "$CI_SERVER_FQDN": "git.example.com",
            "$CI_SERVER_HOST": "git.example.com",
            "$CI_REGISTRY": "git.example.ru:5050"
          },
          hostRules: [{
            hostType: 'npm',
            matchHost: 'https://git.example.com/api/v4/packages/npm/',
            token: 'glpat-xxxxxx'
          }],
          npmrc: "@tools:registry=https://git.example.com/api/v4/packages/npm/\n"
        }
```
I tried to do ESM
```yml
config: |
        export default {
          registryAliases: {
            "$CI_SERVER_FQDN": "git.example.com",
            "$CI_SERVER_HOST": "git.example.com",
            "$CI_REGISTRY": "git.example.ru:5050"
          },
          hostRules: [{
            hostType: 'npm',
            matchHost: 'https://git.example.com/api/v4/packages/npm/',
            token: 'glpat-xxxxxx'
          }],
          npmrc: "@tools:registry=https://git.example.com/api/v4/packages/npm/\n"
        }
```
But that doesn't work either.
