### ISSUE TITLE
Config.js is not picked up

### ISSUE THREAD

**Issue by simPod** [mend/renovate-ce-ee#707]
I tried configuring `RENOVATE_CONFIG_FILE` but renovate seems not to do anything about it. I also have debug logging enabled but see no mention about file config.

Using 9.10.0-full

```yaml
services:
  renovate-ce:
    image: ghcr.io/mend/renovate-ce:9.10.0-full
    ports:
      - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    env_file:
      # Import required settings for Mend Renovate Self-hosted
      - ./mend-renovate.env # Provide a license key and accept the Terms of Service
      # Choose an env file that matches your Git repository
      #- ./github.env
      # - ../env/gitlab.env
      # - ../env/bitbucket.env
      # Import optional settings for Renovate CE
      # - ../env/renovate-server-config.env # Set 'MEND_RNV_SERVER_HOSTNAME' to match server container (ie. http://rnv-ee-server:8080)
      # - ../env/renovate-core.env # Set Renovate CLI configuration options. (ie. `RENOVATE_REPOSITORY_CACHE=enabled`)
      # MinIO S3 storage
      # - ../env/minio.env
    environment:
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Use 'json' when importing logs to reporting tool (eg. Splunk).
      MEND_RNV_REQUEST_LOGGER_ENABLED: true # Set to 'true' to log all incoming API requests to DEBUG logger. Defaults to 'false'.
      # API settings
      MEND_RNV_ADMIN_API_ENABLED: true # Enable incoming API calls. Must set `MEND_RNV_SERVER_API_SECRET` (Hint: check the mend-renovate.env f>
      MEND_RNV_REPORTING_ENABLED: true # Set to 'true' to enable Reporting APIs. (Set `RENOVATE_REPOSITORY_CACHE` on Worker for PR data)
      # If persisting Job logs or DB, set the following environment variables and enable volume mounts for /logs and /db
      MEND_RNV_LOG_HISTORY_DIR: /logs # Persist Renovate job logs. Enable volume mount for /logs
      MEND_RNV_SQLITE_FILE_PATH: /db/renovate-db.sqlite # Persist database to file. Enable volume mount for /db.
      RENOVATE_CONFIG_FILE: "/usr/src/app/config.js"
    volumes:
      # Tip: Create folders in advance to avoid permission issues (ie. when Renovate CLI tries to write logs)
      - ./job-logs:/logs
      - ./db:/db
      - ./config.js:/usr/src/app/config.js
```

<details>
<summary>logs</summary>

```
[+] Running 1/1
 ✔ Container renovate-renovate-ce-1  Recreated                                                                                            0.1s
Attaching to renovate-ce-1
renovate-ce-1  |  INFO: Initializing configuration...
renovate-ce-1  | DEBUG: MEND_RNV_ADMIN_TOKEN is not set, MEND_RNV_GITLAB_PAT will be used instead
renovate-ce-1  |  INFO: validating regex filter
renovate-ce-1  |        "filter": ["/dev/**"]
renovate-ce-1  |  INFO: Configuration initialized successfully
renovate-ce-1  | DEBUG: Resolved configuration
renovate-ce-1  |        "resolvedConfig": {
renovate-ce-1  |          "cronJobSchedulerAll": "0 * * * *",
renovate-ce-1  |          "licenseKey": "***********",
renovate-ce-1  |          "acceptTOS": "y",
renovate-ce-1  |          "versionMismatchPrintInterval": 60,
renovate-ce-1  |          "debugMode": false,
renovate-ce-1  |          "dataHandlerType": "sqlite",
renovate-ce-1  |          "sqlTraceMode": false,
renovate-ce-1  |          "sqliteFilePath": "/db/renovate-db.sqlite",
renovate-ce-1  |          "sqliteVerbose": false,
renovate-ce-1  |          "sqliteExtensionsPaths": ["/usr/src/mend/resources/sqlite/uuid.so"],
renovate-ce-1  |          "serverHttpPort": "8080",
renovate-ce-1  |          "serverHttpDisabled": false,
renovate-ce-1  |          "serverHttpsPort": "8443",
renovate-ce-1  |          "userAgent": "mend-renovate",
renovate-ce-1  |          "syncMode": "bulk",
renovate-ce-1  |          "syncOnStartup": true,
renovate-ce-1  |          "serverApiRoot": "/api",
renovate-ce-1  |          "serverApiSecret": "***********",
renovate-ce-1  |          "adminApiEnabled": true,
renovate-ce-1  |          "requestLoggerEnabled": true,
renovate-ce-1  |          "metricsEnabled": false,
renovate-ce-1  |          "cronAppSync": "0 0,4,8,12,16,20 * * *",
renovate-ce-1  |          "reportingEnabled": true,
renovate-ce-1  |          "enqueueJobsOnStartup": "discovered",
renovate-ce-1  |          "webhookBaseBranches": ["master", "main", "develop"],
renovate-ce-1  |          "webhookBranchPrefixes": ["renovate/"],
renovate-ce-1  |          "webhookUrl": "http://renovate.mydomain.dev/webhook",
renovate-ce-1  |          "webhookName": "renovate",
renovate-ce-1  |          "logHistoryDir": "/logs",
renovate-ce-1  |          "logHistoryTTLDays": 30,
renovate-ce-1  |          "logHistoryCleanupCron": "0 0 * * *",
renovate-ce-1  |          "workerExecutionTimeout": 3600000,
renovate-ce-1  |          "workerHealthPort": "8080",
renovate-ce-1  |          "workerCleanup": "off",
renovate-ce-1  |          "workerCleanupDirs": [
renovate-ce-1  |            "/tmp/renovate/cache",
renovate-ce-1  |            "/tmp/renovate/repos",
renovate-ce-1  |            "/home/ubuntu"
renovate-ce-1  |          ],
renovate-ce-1  |          "diskUsageWarnThreshold": 70,
renovate-ce-1  |          "diskUsageFilters": ["/dev/**"],
renovate-ce-1  |          "maxInactiveCount": 0,
renovate-ce-1  |          "singleJobWorker": false,
renovate-ce-1  |          "kafkaTopicName": "mend-renovate-ee",
renovate-ce-1  |          "kafkaPartitionKeyCandidates": [],
renovate-ce-1  |          "platform": "gitlab",
renovate-ce-1  |          "enableHttp2": false,
renovate-ce-1  |          "disableGlobalAgent": false,
renovate-ce-1  |          "gitlabEndpoint": "https://gitlab.mydomain.eu/api/v4/",
renovate-ce-1  |          "gitlabPat": "***********",
renovate-ce-1  |          "gitlabWebhookSecret": "***********"
renovate-ce-1  |        }
renovate-ce-1  |  INFO: Validating terms of service agreement
renovate-ce-1  |        "input": "y"
renovate-ce-1  |  INFO: Validating Mend license key
renovate-ce-1  |  INFO: You are using an unregistered license key that allows a maximum of 10 repos to be installed. For a free license to install unlimited repos, register at https://www.mend.io/renovate-community”
renovate-ce-1  | DEBUG: Initializing...
renovate-ce-1  |  INFO: Merge Confidence is off; skipping Merge Confidence validation
renovate-ce-1  | DEBUG: Initializing sqlite
renovate-ce-1  | DEBUG: Running sqlite database migration
renovate-ce-1  |        "config": {
renovate-ce-1  |          "migrationsFolder": "/usr/src/mend/core/lib/model/sqlite/drizzle-sqlite/migrations"
renovate-ce-1  |        }
renovate-ce-1  | DEBUG: Database migration success
renovate-ce-1  | DEBUG: Initializing webhooks handler
renovate-ce-1  |  INFO: Using GitLab endpoint
renovate-ce-1  |        "endpoint": "https://gitlab.mydomain.eu/api/v4/"
renovate-ce-1  |  INFO: Using GitLab endpoint: https://gitlab.mydomain.eu/api/v4/
renovate-ce-1  |  INFO: Authenticated as GitLab user
renovate-ce-1  |        "username": "bot"
renovate-ce-1  |  INFO: Renovate Bot platform details
renovate-ce-1  |        "botData": {
renovate-ce-1  |          "id": 89,
renovate-ce-1  |          "name": "bot",
renovate-ce-1  |          "botName": "bot",
renovate-ce-1  |          "endpoint": "https://gitlab.mydomain.eu/api/v4/",
renovate-ce-1  |          "gitAuthor": "bot <bot@bot.com>",
renovate-ce-1  |          "platform": "gitlab"
renovate-ce-1  |        }
renovate-ce-1  | DEBUG: Input clean up config
renovate-ce-1  |        "cleanupConfig": {
renovate-ce-1  |          "cleanupDirs": ["/tmp/renovate/cache", "/tmp/renovate/repos", "/home/ubuntu"],
renovate-ce-1  |          "refDir": "/tmp",
renovate-ce-1  |          "userInputMode": "off"
renovate-ce-1  |        }
renovate-ce-1  |  INFO: Worker file system cleanup handler is disabled
renovate-ce-1  |        "userInputMode": "off",
renovate-ce-1  |        "cleanupDirs": ["/tmp/renovate/cache", "/tmp/renovate/repos", "/home/ubuntu"]
renovate-ce-1  | DEBUG: Initialization completed successfully
renovate-ce-1  |        "renovateVersion": "39.264.0"
renovate-ce-1  |  INFO: Sync and enqueue job startup mode
renovate-ce-1  |        "syncOnStartup": true,
renovate-ce-1  |        "syncMode": "bulk",
renovate-ce-1  |        "enqueueJobsOnStartup": "discovered"
renovate-ce-1  | DEBUG: Performing app sync
Gracefully stopping... (press Ctrl+C again to force)
```

</details>

config.js

```js
module.exports = {
	autodiscover: true,
	autodiscoverFilter: ['/^some/filter$/'],
	repositoryCache: 'enabled',
	hostRules: [
		{
			hostType: 'docker',
			username: 'runner',
			password: 'pwd',
		},
    		{
      			enabled: false,
      			matchHost: 'docker.io',
    		},
		{
			"matchHost": "ghcr.io",
			"hostType": "docker",
			"username": "user",
			"password": 'somepwrd',
		}
	],
};
```
