### ISSUE TITLE
Unable to install Helm chart in rootless mode due to cache folder permissions issue

### ISSUE THREAD

**Issue by interone-ms** [mend/renovate-ce-ee#708]
For compliance reasons we are running in rootless mode, with this values.yaml (chart 9.10.1):

```yaml
cachePersistence:
  enabled: true
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 12021
  runAsGroup: 12021
  fsGroup: 12021
  supplementalGroups:
    - 12021
  seccompProfile:
    type: "RuntimeDefault"
```

Renovate fails to start with ENOENT:

```json
{"name":"mend-renovate","hostname":"renovate-ce-mend-renovate-ce-674fd5c7d7-x5ntd","pid":8,"level":60,"logContext":"6n4G-AKU9j64b9Q6BX2cQ","err":{"errno":-2,"code":"ENOENT","syscall":"mkdir","path":"/tmp/renovate-ee/","message":"ENOENT: no such file or directory, mkdir '/tmp/renovate-ee/'","stack":"Error: ENOENT: no such file or directory, mkdir '/tmp/renovate-ee/'\n    at Object.mkdirSync (node:fs:1364:26)\n    at module.exports.makeDirSync (/usr/src/mend/node_modules/fs-extra/lib/mkdirs/make-dir.js:23:13)\n    at rt.validate (file:///usr/src/mend/src/community.js:1:16895)\n    at rt.init (file:///usr/src/mend/src/community.js:1:7934)\n    at xs (file:///usr/src/mend/src/community.js:5:83677)\n    at file:///usr/src/mend/src/community.js:5:95234\n    at file:///usr/src/mend/src/community.js:5:95240\n    at ModuleJob.run (node:internal/modules/esm/module_job:274:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)"},"msg":"Failure initializing Renovate community edition - exiting...","time":"2025-05-06T12:49:34.170Z","v":0}
```

The cause seems to be that the chart creates and mounts `/tmp/renovate`, whereas Renovate tries to create (and use) `/tmp/renovate-ee/`.

**Comment by Gabriel-Ladzaretti** [comment]
disable the cache volume via: 
- https://github.com/mend/renovate-ce-ee/blob/a18add1e312a202fe842513f14e6b9c7b5bed315/helm-charts/mend-renovate-ce/values.yaml#L224

\+ in order the ro file system to work u need to both mount `/tmp` and `/opt/contianerbase`


```yaml
  extraVolumes:
    - name: mend-renovate-ee-containerbase-volume
      emptyDir: { }
    - name: mend-renovate-ee-cache-volume
      emptyDir: { }

  extraVolumeMounts:
    - name: mend-renovate-ee-containerbase-volume
      mountPath: /opt/containerbase
    - name: mend-renovate-ee-cache-volume
      mountPath: /tmp
```
