### ISSUE TITLE
Renovate-CE mendRnvWorkerCleanupDirs looks like not working

### ISSUE THREAD

**Issue by weijiany** [mend/renovate-ce-ee#713]
### Problem
Despite this configuration, certain directories like `pnpm` and `cache` are not being automatically cleaned up. This is causing storage issues over time as these directories continue to grow.

### Environment
- Mend Renovate CE version: 9.10.1
- Infrastructure: AWS EBS
- Storage configuration: AWS EBS volumes

### Expected behavior
All directories specified in `mendRnvWorkerCleanupDirs` should be automatically cleaned up after jobs complete.

### Actual behavior
Some directories (specifically the pnpm and cache directories) remain filled with data and are not being cleaned up.

### Additional information
This issue appears to be specific to the worker cleanup process. The cleanup functionality worked in previous versions but seems to be broken in the current version I'm using.

### Configuration
```yaml
renovate:
  ...
  mendRnvWorkerCleanupDirs: '/opt/containerbase, /tmp/renovate/cache, /tmp/renovate/repos, /home/ubuntu, /tmp/renovate/.pnpm-store, /tmp/renovate/job-logs'
cachePersistence:
  enabled: true
  storageClass: "gp3"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
...
```

Hope you can help me with this issue.
